export const ResponseCodes = {
  SUCCESS: {
    BASE_SUCESS: 'SUCCESS',
    AUTH_SUCCESS: 'AUTH_SUCCESS',
    USER_CREATED: 'USER_CREATED',
  },
  ERROR: {
    AUTH_FAILED: 'AUTH_FAILED',
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
    PASSWORD_MISMATCH: 'PASSWORD_MISMATCH',
    USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    UNAUTHORIZED: 'UNAUTHORIZED',
    FORBIDDEN: 'FORBIDDEN',
    NOT_FOUND: 'NOT_FOUND',
  },
};
