export const ConfigKeys = {
  DATABASE_MONGO_URI: 'database.mongo_uri',
  AUTH_SERVICE_HOST: 'auth_service.host',
  AUTH_SERVICE_PORT: 'auth_service.port',
  AUTH_SERVICE_GRPC_PORT: 'auth_service.grpc_port',
  AUTH_SERVICE_TCP_PORT: 'auth_service.tcp_port',
  JWT_SECRET: 'jwt.secret',
  MAIL_HOST: 'mail.host',
  MAIL_USERNAME: 'mail.username',
  MAIL_PASSWORD: 'mail.password',
  API_GATEWAY_HOST: 'api_gateway.host',
  API_GATEWAY_PORT: 'api_gateway.port',
  API_GATEWAY_URL: 'api_gateway.url',
  API_GATEWAY_EMAIL_VERIFICATION: 'api_gateway.email_verification',
  GOOGLE_OAUTH_CLIENT_ID: 'oauth_google.client_id',
  GOOGLE_OAUTH_CLIENT_SECRET: 'oauth_google.client_secret',
  GOOGLE_OAUTH_CALLBACK_URL: 'oauth_google.callback_url',
  GOOGLE_OAUTH_AUTHORIZATION_URL: 'oauth_google.authorization_url',
  GOOGLE_OAUTH_TOKEN_URL: 'oauth_google.token_url',
  GOOGLE_OAUTH_USERINFO_URL: 'oauth_google.profile_url',
};
